version: '3'

volumes:
  database-data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - database-data:/var/lib/postgressql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static:/app/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - db
  nginx:
    build: 
      context: ./nginx.conf/
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "7000:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/app/backend_static
      - media:/app/media
    depends_on:
      - frontend     
      - backend
