version: '3'

volumes:
  database-data:
  static:
  media:
  redoc:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - database-data:/var/lib/postgressql/data

  backend:
    image: jfilchin/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/backend_static
      - media:/app/media
      - redoc:/app/docs
    depends_on:
      - db

  frontend:
    image: jfilchin/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: jfilchin/foodgram_gateway
    env_file: .env
    ports:
      - "7000:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/app/backend_static
      - media:/app/media
    depends_on:
      - frontend
      - backend
