# Generated by Django 3.2.3 on 2023-12-15 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Допускаются латинские буквы, цифры и _ ', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Уникальный адрес тег'),
        ),
    ]
