# Generated by Django 3.2.3 on 2023-12-15 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Цветовой код в формате #49B64E'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Допускаются латинские буквы, цифры и _ ', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Уникальный адрес тег'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название тэга'),
        ),
    ]
