# Generated by Django 3.2.3 on 2023-12-16 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20231215_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Допускаются латинские буквы, цифры и _ ', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Уникальный идентификатор'),
        ),
    ]
