# Generated by Django 3.2.3 on 2023-12-17 08:14

import django.core.validators
from django.db import migrations, models

import api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231215_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Допустимые символы: . + - ', regex='^[\\w.@+-]+\\Z'), api.validators.UsernameValidator()], verbose_name='Пользователь'),
        ),
    ]
